package com.dv.mms.app.domain.master;

// Generated Oct 9, 2010 10:54:31 AM by Hibernate Tools 3.2.4.GA

/**
 * MmGoodsreceiptdetail generated by hbm2java
 */
public class MmGoodsreceiptdetail implements java.io.Serializable {

	private Integer grdNo;
	private MmGoodsreceiptheader mmGoodsreceiptheader;
	private MmItem mmItem;
	private String grhDesc;
	private double grhQty;

	public MmGoodsreceiptdetail() {
	}

	public MmGoodsreceiptdetail(MmGoodsreceiptheader mmGoodsreceiptheader,
			MmItem mmItem, String grhDesc, double grhQty) {
		this.mmGoodsreceiptheader = mmGoodsreceiptheader;
		this.mmItem = mmItem;
		this.grhDesc = grhDesc;
		this.grhQty = grhQty;
	}

	public Integer getGrdNo() {
		return this.grdNo;
	}

	public void setGrdNo(Integer grdNo) {
		this.grdNo = grdNo;
	}

	public MmGoodsreceiptheader getMmGoodsreceiptheader() {
		return this.mmGoodsreceiptheader;
	}

	public void setMmGoodsreceiptheader(
			MmGoodsreceiptheader mmGoodsreceiptheader) {
		this.mmGoodsreceiptheader = mmGoodsreceiptheader;
	}

	public MmItem getMmItem() {
		return this.mmItem;
	}

	public void setMmItem(MmItem mmItem) {
		this.mmItem = mmItem;
	}

	public String getGrhDesc() {
		return this.grhDesc;
	}

	public void setGrhDesc(String grhDesc) {
		this.grhDesc = grhDesc;
	}

	public double getGrhQty() {
		return this.grhQty;
	}

	public void setGrhQty(double grhQty) {
		this.grhQty = grhQty;
	}

}
