package com.dv.mms.app.domain.master;

// Generated Oct 9, 2010 10:54:31 AM by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * MmGoodsissueheader generated by hbm2java
 */
public class MmGoodsissueheader implements java.io.Serializable {

	private Integer gihNo;
	private Date gihDate;
	private Set mmGoodsissuedetails = new HashSet(0);
	private MmVehicle mmVehicle;
	private MmUser mmUser;
	private String status;

	public MmGoodsissueheader() {
	}

	public MmGoodsissueheader(Integer gihNo) {
		this.gihNo = gihNo;
	}

	public MmGoodsissueheader(Integer gihNo, Date gihDate,
			Set mmGoodsissuedetails, MmVehicle mmVehicle, MmUser mmUser,String status) {
		super();
		this.gihNo = gihNo;
		this.gihDate = gihDate;
		this.mmGoodsissuedetails = mmGoodsissuedetails;
		this.mmVehicle = mmVehicle;
		this.mmUser = mmUser;
		this.status = status;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public MmVehicle getMmVehicle() {
		return mmVehicle;
	}

	public void setMmVehicle(MmVehicle mmVehicle) {
		this.mmVehicle = mmVehicle;
	}

	public MmUser getMmUser() {
		return mmUser;
	}

	public void setMmUser(MmUser mmUser) {
		this.mmUser = mmUser;
	}

	public Integer getGihNo() {
		return this.gihNo;
	}

	public void setGihNo(Integer gihNo) {
		this.gihNo = gihNo;
	}

	public Date getGihDate() {
		return this.gihDate;
	}

	public void setGihDate(Date gihDate) {
		this.gihDate = gihDate;
	}

	public Set getMmGoodsissuedetails() {
		return this.mmGoodsissuedetails;
	}

	public void setMmGoodsissuedetails(Set mmGoodsissuedetails) {
		this.mmGoodsissuedetails = mmGoodsissuedetails;
	}

}
