package com.dv.mms.app.domain.master;

// Generated Oct 9, 2010 10:54:31 AM by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * MmGoodsreceiptheader generated by hbm2java
 */
public class MmGoodsreceiptheader implements java.io.Serializable {

	private Integer grhNo;
	private Date grhDate;
	private MmPoheader mmPoheader;
	private Set mmGoodsreceiptdetails = new HashSet(0);

	public MmGoodsreceiptheader() {
	}

	public MmGoodsreceiptheader(Date grhDate, MmPoheader mmPoheader,
			Set mmGoodsreceiptdetails) {
		this.grhDate = grhDate;
		this.mmPoheader = mmPoheader;
		this.mmGoodsreceiptdetails = mmGoodsreceiptdetails;
	}

	public Integer getGrhNo() {
		return this.grhNo;
	}

	public void setGrhNo(Integer grhNo) {
		this.grhNo = grhNo;
	}

	public Date getGrhDate() {
		return this.grhDate;
	}

	public void setGrhDate(Date grhDate) {
		this.grhDate = grhDate;
	}

	public MmPoheader getMmPoheader() {
		return this.mmPoheader;
	}

	public void setMmPoheader(MmPoheader mmPoheader) {
		this.mmPoheader = mmPoheader;
	}

	public Set getMmGoodsreceiptdetails() {
		return this.mmGoodsreceiptdetails;
	}

	public void setMmGoodsreceiptdetails(Set mmGoodsreceiptdetails) {
		this.mmGoodsreceiptdetails = mmGoodsreceiptdetails;
	}

}
