package com.dv.mms.app.domain.master;

// Generated Oct 9, 2010 10:54:31 AM by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * MmPoheader generated by hbm2java
 */
public class MmPoheader implements java.io.Serializable {

	private Integer poNo;
	private Date poDate;
	private MmReqheader mmReqheader;
	private MmVendor mmVendor;
	private Set mmPodetails = new HashSet(0);
	private String poStatus;
	private String poType;

	public MmPoheader() {
	}

	public MmPoheader(Date poDate, MmReqheader mmReqheader, MmVendor mmVendor,
			Set mmPodetails,String poStatus,String poType) {
		this.poDate = poDate;
		this.mmReqheader = mmReqheader;
		this.mmVendor = mmVendor;
		this.mmPodetails = mmPodetails;
		this.poStatus = poStatus;
		this.poType = poType;
	}

	public String getPoType() {
		return poType;
	}

	public void setPoType(String poType) {
		this.poType = poType;
	}

	public String getPoStatus() {
		return poStatus;
	}

	public void setPoStatus(String poStatus) {
		this.poStatus = poStatus;
	}

	public Integer getPoNo() {
		return this.poNo;
	}

	public void setPoNo(Integer poNo) {
		this.poNo = poNo;
	}

	public Date getPoDate() {
		return this.poDate;
	}

	public void setPoDate(Date poDate) {
		this.poDate = poDate;
	}

	public MmReqheader getMmReqheader() {
		return this.mmReqheader;
	}

	public void setMmReqheader(MmReqheader mmReqheader) {
		this.mmReqheader = mmReqheader;
	}

	public MmVendor getMmVendor() {
		return this.mmVendor;
	}

	public void setMmVendor(MmVendor mmVendor) {
		this.mmVendor = mmVendor;
	}

	public Set getMmPodetails() {
		return this.mmPodetails;
	}

	public void setMmPodetails(Set mmPodetails) {
		this.mmPodetails = mmPodetails;
	}

}
