package com.dv.mms.app.domain.master;

// Generated Oct 9, 2010 10:54:31 AM by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * MmReqheader generated by hbm2java
 */
public class MmReqheader implements java.io.Serializable {

	private Integer rhNo;
	private Date rhDate;
	private String status;
	private MmUser Requestor;
	private Set mmReqdetails = new HashSet(0);

	public MmReqheader() {
	}

	public MmReqheader(Date rhDate, String status, MmUser Requestor,
			Set mmReqdetails) {
		this.rhDate = rhDate;
		this.status = status;
		this.Requestor = Requestor;
		this.mmReqdetails = mmReqdetails;
	}

	public Integer getRhNo() {
		return this.rhNo;
	}

	public void setRhNo(Integer rhNo) {
		this.rhNo = rhNo;
	}

	public Date getRhDate() {
		return this.rhDate;
	}

	public void setRhDate(Date rhDate) {
		this.rhDate = rhDate;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public MmUser getRequestor() {
		return this.Requestor;
	}

	public void setRequestor(MmUser Requestor) {
		this.Requestor = Requestor;
	}

	public Set getMmReqdetails() {
		return this.mmReqdetails;
	}

	public void setMmReqdetails(Set mmReqdetails) {
		this.mmReqdetails = mmReqdetails;
	}

}
