package com.dv.mms.app.domain.master;

// Generated Oct 9, 2010 10:54:31 AM by Hibernate Tools 3.2.4.GA

/**
 * MmReqdetail generated by hbm2java
 */
public class MmReqdetail implements java.io.Serializable {

	private Integer rdNo;
	private MmReqheader mmReqheader;
	private MmItem mmItem;
	private String itDesc;
	private double rdQty;
	private double poQty=0;

	public double getPoQty() {
		return poQty;
	}

	public void setPoQty(double poQty) {
		this.poQty = poQty;
	}

	public MmReqdetail() {
	}

	public MmReqdetail(MmReqheader mmReqheader, MmItem mmItem, String itDesc,
			double rdQty) {
		this.mmReqheader = mmReqheader;
		this.mmItem = mmItem;
		this.itDesc = itDesc;
		this.rdQty = rdQty;
	}

	public Integer getRdNo() {
		return this.rdNo;
	}

	public void setRdNo(Integer rdNo) {
		this.rdNo = rdNo;
	}

	public MmReqheader getMmReqheader() {
		return this.mmReqheader;
	}

	public void setMmReqheader(MmReqheader mmReqheader) {
		this.mmReqheader = mmReqheader;
	}

	public MmItem getMmItem() {
		return this.mmItem;
	}

	public void setMmItem(MmItem mmItem) {
		this.mmItem = mmItem;
	}

	public String getItDesc() {
		return this.itDesc;
	}

	public void setItDesc(String itDesc) {
		this.itDesc = itDesc;
	}

	public double getRdQty() {
		return this.rdQty;
	}

	public void setRdQty(double rdQty) {
		this.rdQty = rdQty;
	}

}
