package com.dv.mms.app.domain.master;

// Generated Oct 9, 2010 10:54:31 AM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

/**
 * MmVendor generated by hbm2java
 */
public class MmVendor implements java.io.Serializable {

	/**
	 * @param id
	 * @param name
	 * @param add1
	 * @param add2
	 * @param add3
	 * @param add4
	 * @param venType
	 * @param mmPoheaders
	 */
	public MmVendor(Integer id, String name, String add1, String add2,
			String add3, String add4, String venType, Set mmPoheaders) {
		super();
		this.id = id;
		this.name = name;
		this.add1 = add1;
		this.add2 = add2;
		this.add3 = add3;
		this.add4 = add4;
		this.venType = venType;
		this.mmPoheaders = mmPoheaders;
	}

	private Integer id;
	private String name;
	private String add1;
	private String add2;
	private String add3;
	private String add4;
	private String venType;
	private Set mmPoheaders = new HashSet(0);

	public MmVendor() {
	}

	public MmVendor(String name, String add1, String add2, String add3,
			String add4, String venType, Set mmPoheaders) {
		this.name = name;
		this.add1 = add1;
		this.add2 = add2;
		this.add3 = add3;
		this.add4 = add4;
		this.venType = venType;
		this.mmPoheaders = mmPoheaders;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAdd1() {
		return this.add1;
	}

	public void setAdd1(String add1) {
		this.add1 = add1;
	}

	public String getAdd2() {
		return this.add2;
	}

	public void setAdd2(String add2) {
		this.add2 = add2;
	}

	public String getAdd3() {
		return this.add3;
	}

	public void setAdd3(String add3) {
		this.add3 = add3;
	}

	public String getAdd4() {
		return this.add4;
	}

	public void setAdd4(String add4) {
		this.add4 = add4;
	}

	public String getVenType() {
		return this.venType;
	}

	public void setVenType(String venType) {
		this.venType = venType;
	}

	public Set getMmPoheaders() {
		return this.mmPoheaders;
	}

	public void setMmPoheaders(Set mmPoheaders) {
		this.mmPoheaders = mmPoheaders;
	}

}
